n = int(input('Digite um número: '))
print(f'O dobro de {n} é {n*2}.')
print(f'O triplo de {n} é {n*3}')
print(f'A raiz Quadrada de {n} é {n**(1/2):.3f}.')
print(f'A raiz quadrada de {n} é {pow(n,(1/2)):.3f}')